portal: walrus.site
package: "0xdf9033cac39b7a9b9f76fb6896c9fc5283ba730d6976a2b1d85ad1e6036c3272"
general:
  walrus_binary: walrus
  gas_budget: 170000000

name: "Probably Nothing"
description: "An awesome walrus-themed snake game"
site:
  index: index.html
  files:
    - "**/*"
  exclude:
    - ".git/*"
    - ".git/**/*"
    - "node_modules/*"
    - "node_modules/**/*"